### ISSUE TITLE
README contains a broken link

### ISSUE THREAD

**Issue by kobigurk** [LedgerHQ/app-celo-spender#4]
![image](https://user-images.githubusercontent.com/3520024/132326700-1aa14761-6487-4f7c-9d54-fed8f9ac3460.png)

https://medium.com/@Ledger/dynamic-secure-applications-with-bolos-and-ledger-blue-a-use-case-with-ethereum-and-the-dao-6be91260e89f#.204qgmogo

**Comment by jibeee** [comment]
Thanks!
